### ISSUE TITLE
Pull more issues from prior user reports and punchlists into github/issues

### ISSUE THREAD

**Issue by mattmathis** [mattmathis/scvfa-webtools#12]
There are many (mostly) minor issues on the legacy punch list that have not been imported as issues.

 See [SCVFA post launch punch list](https://docs.google.com/document/d/1VbvTGm50RfWBGXTRszGeQSTV9bZ-fRb-3zt_XZl_Fsc/edit#heading=h.mm0dcsae0vc)

**Comment by mbryant412** [comment]
I believe all of these issues have been taken care of. Let me know otherwise.
