### ISSUE TITLE
Revise Join and renew workflows to match the new membership model

### ISSUE THREAD

**Issue by mattmathis** [mattmathis/scvfa-webtools#14]
Ask for only minimal information in the initial join and resubscription.

Add buttons in the member console (and you have successfully joined pages or notices) to update the informational fields.

I have seen a prototype with fewer questions on the initial join, but it seems to have disappears (or at least some of the join links still go to the old workflow.)

Note that this may  depend on #13.

**Comment by mbryant412** [comment]
This completed and tested. Please create your own test member.
