### ISSUE TITLE
Registrant/Administrative Contact info

### ISSUE THREAD

**Issue by mbryant412** [mattmathis/scvfa-webtools#15]
Please specify:
Organization
First/Last Name
Title/Role
Postal Address
Email Address
Phone Number

Domain Contacts at Enom

**Comment by mbryant412** [comment]
Add P1 Label please.

**Comment by mattmathis** [comment]
These are for you to add me as a delegate on SCVFA within New Skye?
SCVFA (or perhaps New Skye)
Matthew Mathis
Internet Engineer (or perhaps webmaster*)
PO box  390335, Mountain View CA 94039
matt.mathis@gmail.com
412.654.7529

* If this question is which field in the registrar's records use admin 
I do not currently have any domains at enom .  I think I had an account there at one time but it seems to have lapsed.

**Comment by mbryant412** [comment]
These are for Owner/Administrative contacts in Enom for domains fiddlers.org and scvfa.org.

 

Thank you,

Michael

 

From: Matt Mathis ***@***.***>
Reply-To: mattmathis/scvfa-webtools ***@***.***>
Date: Friday, January 19, 2024 at 10:13 AM
To: mattmathis/scvfa-webtools ***@***.***>
Cc: Michael Bryant ***@***.***>, Author ***@***.***>
Subject: Re: [mattmathis/scvfa-webtools] Registrant/Administrative Contact info (Issue #15)

 

These are for you to add me as a delegate on SCVFA within New Skye?
SCVFA (or perhaps New Skye)
Matthew Mathis
Internet Engineer (or perhaps webmaster*)
PO box 390335, Mountain View CA 94039
***@***.***
412.654.7529
If this question is which field in the registrar's records use admin
I do not currently have any domains at enom . I think I had an account there at one time but it seems to have lapsed.

**Comment by mbryant412** [comment]
I have changed Regstrant/Admin Contacts at Enom for fiddlers.org/scvfa.org. I am listed as Billing/Technical per our MOU. You should receive consent emails that need to be verified. Once verified we can close issue.

**Comment by mattmathis** [comment]
I'm not finding the right login portal.   enom only shows my other domains that were moved to hover.   Does it show a handle for me?   The address confirmation email from name-services.com does not give any useful information.

BTW the SOA for fiddlers reveals your personal address:
 fiddlers.org.		86400	IN	SOA	ns1.newskyehosting.com. mbryant.sonic.net. 2024011301 3600 1800 1209600 86400

**Comment by mbryant412** [comment]
There is no log in for you. Did you get the consent emails?

**Comment by mbryant412** [comment]
![FiddlerContact](https://github.com/mattmathis/scvfa-webtools/assets/157147773/4bc1313f-06e3-4c50-a361-91fb26c30a21)
![scvfaContact](https://github.com/mattmathis/scvfa-webtools/assets/157147773/d6f0a34d-1dc6-4500-aafa-ca82c5e27758)

**Comment by mattmathis** [comment]
Thanks
