### ISSUE TITLE
Integrate PMPpro and existing lists on MailChimp

### ISSUE THREAD

**Issue by mattmathis** [mattmathis/scvfa-webtools#3]
Test the following sequence:
- User joins announce
-  User joins performances
- User becomes a member
When PMP updates the user in MC, does it clobber the existing group tags?

(Test by manually adding a test user to MC, in the PNP audience)

Design an efficient MC update process, given the outcome of this experiment.

**Comment by mattmathis** [comment]
Merging is not a problem, because each tag or attribute has its own column, and PMP only  asserts the columns it  owns, (PMP*), so it never interferes with non-PMP columns. 

Note that PMP can simultaneously update multiple audiences.

The MC "segments" can do logical operations on tags or attributes, so we can construct an all member segment.

**Comment by mattmathis** [comment]
Since the initial import did not include all member types and was to the wrong audience, plan to delete the audience entirely and re import PMP into the SCVFA audience.   Steps:

- [x] Stop exporting to the PMP audience
- [x] Delete the PMP audience entirely
- [x] Properly reimport everybody into SCVFA
- [x] build a proper segment for SCVFA members

**Comment by mbryant412** [comment]
Please export your PMP audience and SCVFA audience. Color code PMP, add records to SCVFA table and use Excel find duplicates by highlight color. Any highlighted records left after are not already in SCVFA but I believe they are all in there except any new members since beginning of January. We can then change the export destination to the SCVFA audience. If that is your goal, why not switch the export destination now. Should we?

**Comment by mattmathis** [comment]
The PMP audience within SCVFA is just testers and people who happened to join at the right time.  They should all be overwritten with fresh data. (step 3 above).

I am doing the matching in python, not excel, and have confirmed how the API interacts with existing manual data.   The key is that they use different columns, and do not overwrite each other's  data.  MC's Tags each have their own  column, so adding or deleting one does not affect any other Tags.   I want to move the PMP generated data into the SCVFA Audience.   I can define a MC 'segment' which matches all  PMP members (since PMP labels each level differently)

**Comment by mattmathis** [comment]
Please let me move the  PMPro data to the SCVFA audience- I can tightly coordinate with other potential editors, and take snapshots at the right times to robustly avoid any lost data.

**Comment by mbryant412** [comment]
Yes, please do and let me know when PMP audience is deleted so we can remove references in PMP dashboard.

**Comment by mattmathis** [comment]
Everything above is DONE.

There are now three new MailChimp segments (i.e. expressions on  columns):
1. draftMembers - Exported from PMP and updated (tracked) in real time
2.  missingMembers - Members in PMP but not Susan's manually curated list 
3.  extraMembers - Members in Susan's manually curated list, but not PMP  (93 entries!)

I manually reviewed all of item 2, and added 9 people to Susan's manually curated list.      The remainders are all corner cases:
1. Test members
2. Four members who do not have real email addresses 
3. Two members who capitalized their email address differently, and may have tickled a MC merge bug 
4. Two members who have multiple email addresses and are subscribed differently 

At this point MC is primed to send the Feb newsletter, using my update to Susan's manually curated list.

Still to be done (reduce to p2 for the time being):
1. Audit and thin extraMembers.  This may require policy input from people with history, etc
2. Resolve all missingMembers.  Do we need code, or just manually hack some entries?
3. Consider switching MC to use the fully automated Member list (renamed from draftMembers)
4. Evaluate member expiration and consider adding grace and/or expired membership statuses.

**Comment by mbryant412** [comment]
Can we close any of the 13 issues remaining?
