### ISSUE TITLE
Install a better plugin for parsing phone numbers

### ISSUE THREAD

**Issue by mattmathis** [mattmathis/scvfa-webtools#5]
See [Elementor Telephone Validation Formatting - Ability to Remove Dash "-" in Field Validation Code #7580](https://github.com/elementor/elementor/issues/7580) for clues.

Or  ask PMPro tech support what they recommend.

**Comment by mbryant412** [comment]
When the telephone number is entered as 10 digits, the resulting export from PMP is in NANP with parens around the area code.

**Comment by ray-chen** [comment]
testing 1 2 3 testing
