### ISSUE TITLE
Proof membership notification email messages

### ISSUE THREAD

**Issue by mattmathis** [mattmathis/scvfa-webtools#6]
I wanted to take a look at testing email templates but we didn’t get a chance to go over them this morning. Would you please take a look at them with Susan? Here are steps:

Go here (log in first): 

https://www.fiddlers.org/wp-admin/admin.php?page=pmpro-emailtemplates

Choose Memberships -> Settings

- In the breadcrumb menus choose Email Templates
- Choose a template from the Email Template dropdown (see, notes below)
- Change the Send a test email to text box to your email address (currently has my address)
- Click Save Template and Send Email
- Check your email to see test email

Edits can be performed in the Body text area of the Email templates window.
 Notes: Only emails with the unchecked Disable email checkbox are in use at this time. These are: 

- Cancel
- Checkout – Check/PayPal Express/Paid
- Membership – Expired/Expiring

 When you select a template a description appears below the dropdown menu. 

The plugin email functions off the payment gateways so there is no way for it to determine whether a member is new or renewing.

To address this, you could change first line in checkout letters to “Welcome and Thank you for your membership/renewal to !!sitename!!.” in the first line of the Checkout letters.

**Comment by mattmathis** [comment]
Susan tentatively approved all except cancel.     I will walk her through editing them.   This is good enough for now, so I am going to move it to P2.

**Comment by mbryant412** [comment]
Once edited please close issue
