### ISSUE TITLE
Decent mail client for Matt

### ISSUE THREAD

**Issue by mattmathis** [mattmathis/scvfa-webtools#7]
This should be easy for non 2fa servers, but I am stuck for all 2fa accounts.

**Comment by mattmathis** [comment]
Thunderbird works well enough for non-2fa accounts.

**Comment by mbryant412** [comment]
I don't think there is a standalone email client with 2FA. There are however paid solutions available.

**Comment by mattmathis** [comment]
Can you suggest an email service for less secure (non-2fa)  email?   For SCVFA, I will use the native mail system, but I have this problem for other domains.  e.g. about a dozen accounts that are very low volume critical messages that I often overlook in my gmail.

**Comment by mbryant412** [comment]
Aside from the ones you already know about maybe Zoho? I still think standalone client is best. Of those, Thunderbird and Apple mail standout:
https://www.pcmag.com/picks/best-email-clients

**Comment by mattmathis** [comment]
Thunderbird can do OAUTH2, so 2FA is not a problem.
