### ISSUE TITLE
Tools  for inspecting DMARC summary reports

### ISSUE THREAD

**Issue by mattmathis** [mattmathis/scvfa-webtools#9]
There are probably tools to ingest  a mailbox of reports to produce a unified report.

**Comment by mbryant412** [comment]
We'll defer to your expertise on this one.

**Comment by mattmathis** [comment]
Wrote a simple tool for parsing  DMARC reports.    See src/DMARC-tools/dmarc-parser.py

Also: pip install attachment-downloader to use imap to fetch the reports from postmaster@fiddlers.org

TODO: Parse DMARC RUF reports (we may not have seen any.)

Consider this done for the time being.
